/*
 * This file is generated by jOOQ.
 */
package com.example.cacophony.jooq.routines;


import com.example.cacophony.jooq.Cacophony;

import java.util.UUID;

import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class GenRandomUuid7 extends AbstractRoutine<UUID> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>cacophony.gen_random_uuid7.RETURN_VALUE</code>.
     */
    public static final Parameter<UUID> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.UUID, false, false);

    /**
     * Create a new routine call instance
     */
    public GenRandomUuid7() {
        super("gen_random_uuid7", Cacophony.CACOPHONY, DSL.comment(""), SQLDataType.UUID);

        setReturnParameter(RETURN_VALUE);
    }
}
