/*
 * This file is generated by jOOQ.
 */
package com.example.cacophony.jooq;


import com.example.cacophony.jooq.tables.CUser;
import com.example.cacophony.jooq.tables.Channel;
import com.example.cacophony.jooq.tables.ChannelVisibility;
import com.example.cacophony.jooq.tables.Chat;
import com.example.cacophony.jooq.tables.Conversation;
import com.example.cacophony.jooq.tables.ConversationType;
import com.example.cacophony.jooq.tables.Databasechangelog;
import com.example.cacophony.jooq.tables.Databasechangeloglock;
import com.example.cacophony.jooq.tables.Message;
import com.example.cacophony.jooq.tables.MessageReact;
import com.example.cacophony.jooq.tables.React;
import com.example.cacophony.jooq.tables.UserConversation;
import com.example.cacophony.jooq.tables.UserRole;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.DSL;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Cacophony extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cacophony</code>
     */
    public static final Cacophony CACOPHONY = new Cacophony();

    /**
     * The table <code>cacophony.c_user</code>.
     */
    public final CUser C_USER = CUser.C_USER;

    /**
     * The table <code>cacophony.channel</code>.
     */
    public final Channel CHANNEL = Channel.CHANNEL;

    /**
     * The table <code>cacophony.channel_visibility</code>.
     */
    public final ChannelVisibility CHANNEL_VISIBILITY = ChannelVisibility.CHANNEL_VISIBILITY;

    /**
     * The table <code>cacophony.chat</code>.
     */
    public final Chat CHAT = Chat.CHAT;

    /**
     * The table <code>cacophony.conversation</code>.
     */
    public final Conversation CONVERSATION = Conversation.CONVERSATION;

    /**
     * The table <code>cacophony.conversation_type</code>.
     */
    public final ConversationType CONVERSATION_TYPE = ConversationType.CONVERSATION_TYPE;

    /**
     * The table <code>cacophony.databasechangelog</code>.
     */
    public final Databasechangelog DATABASECHANGELOG = Databasechangelog.DATABASECHANGELOG;

    /**
     * The table <code>cacophony.databasechangeloglock</code>.
     */
    public final Databasechangeloglock DATABASECHANGELOGLOCK = Databasechangeloglock.DATABASECHANGELOGLOCK;

    /**
     * The table <code>cacophony.message</code>.
     */
    public final Message MESSAGE = Message.MESSAGE;

    /**
     * The table <code>cacophony.message_react</code>.
     */
    public final MessageReact MESSAGE_REACT = MessageReact.MESSAGE_REACT;

    /**
     * The table <code>cacophony.react</code>.
     */
    public final React REACT = React.REACT;

    /**
     * The table <code>cacophony.user_conversation</code>.
     */
    public final UserConversation USER_CONVERSATION = UserConversation.USER_CONVERSATION;

    /**
     * The table <code>cacophony.user_role</code>.
     */
    public final UserRole USER_ROLE = UserRole.USER_ROLE;

    /**
     * No further instances allowed
     */
    private Cacophony() {
        super(DSL.name("cacophony"), null, DSL.comment(""));
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            CUser.C_USER,
            Channel.CHANNEL,
            ChannelVisibility.CHANNEL_VISIBILITY,
            Chat.CHAT,
            Conversation.CONVERSATION,
            ConversationType.CONVERSATION_TYPE,
            Databasechangelog.DATABASECHANGELOG,
            Databasechangeloglock.DATABASECHANGELOGLOCK,
            Message.MESSAGE,
            MessageReact.MESSAGE_REACT,
            React.REACT,
            UserConversation.USER_CONVERSATION,
            UserRole.USER_ROLE
        );
    }
}
