/*
 * This file is generated by jOOQ.
 */
package com.example.cacophony.jooq;

import com.example.cacophony.jooq.routines.GenRandomUuid7;

import java.util.UUID;

import org.jooq.Configuration;
import org.jooq.Field;

/**
 * Convenience access to all stored procedures and functions in cacophony.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Routines {

    /**
     * Call <code>cacophony.gen_random_uuid7</code>
     */
    public static UUID genRandomUuid7(Configuration configuration) {
        GenRandomUuid7 f = new GenRandomUuid7();

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>cacophony.gen_random_uuid7</code> as a field.
     */
    public static Field<UUID> genRandomUuid7() {
        GenRandomUuid7 f = new GenRandomUuid7();

        return f.asField();
    }
}
