apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example
spec:
  ipAddressPools:
  - local-pool

---

apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: local-pool
spec:
  addresses:
  - 172.20.255.1-172.20.255.255