/*
 * This file is generated by jOOQ.
 */
package com.example.cacophony.jooq.tables.records;


import com.example.cacophony.jooq.tables.ChannelVisibility;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ChannelVisibilityRecord extends UpdatableRecordImpl<ChannelVisibilityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cacophony.channel_visibility.visibility</code>.
     */
    public void setVisibility(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>cacophony.channel_visibility.visibility</code>.
     */
    public String getVisibility() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ChannelVisibilityRecord
     */
    public ChannelVisibilityRecord() {
        super(ChannelVisibility.CHANNEL_VISIBILITY);
    }

    /**
     * Create a detached, initialised ChannelVisibilityRecord
     */
    public ChannelVisibilityRecord(String visibility) {
        super(ChannelVisibility.CHANNEL_VISIBILITY);

        setVisibility(visibility);
        resetTouchedOnNotNull();
    }
}
