/*
 * This file is generated by jOOQ.
 */
package com.example.cacophony.jooq.tables.records;

import com.example.cacophony.jooq.tables.ConversationType;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ConversationTypeRecord extends UpdatableRecordImpl<ConversationTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cacophony.conversation_type.type</code>.
     */
    public void setType(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>cacophony.conversation_type.type</code>.
     */
    public String getType() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ConversationTypeRecord
     */
    public ConversationTypeRecord() {
        super(ConversationType.CONVERSATION_TYPE);
    }

    /**
     * Create a detached, initialised ConversationTypeRecord
     */
    public ConversationTypeRecord(String type) {
        super(ConversationType.CONVERSATION_TYPE);

        setType(type);
        resetTouchedOnNotNull();
    }
}
