/*
 * This file is generated by jOOQ.
 */
package com.example.cacophony.jooq.tables.records;


import com.example.cacophony.jooq.tables.CUser;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class CUserRecord extends UpdatableRecordImpl<CUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cacophony.c_user.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>cacophony.c_user.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>cacophony.c_user.username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>cacophony.c_user.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>cacophony.c_user.email</code>.
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>cacophony.c_user.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>cacophony.c_user.password</code>.
     */
    public void setPassword(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>cacophony.c_user.password</code>.
     */
    public String getPassword() {
        return (String) get(3);
    }

    /**
     * Setter for <code>cacophony.c_user.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>cacophony.c_user.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>cacophony.c_user.updated_at</code>.
     */
    public void setUpdatedAt(OffsetDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>cacophony.c_user.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>cacophony.c_user.user_role</code>.
     */
    public void setUserRole(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>cacophony.c_user.user_role</code>.
     */
    public String getUserRole() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CUserRecord
     */
    public CUserRecord() {
        super(CUser.C_USER);
    }

    /**
     * Create a detached, initialised CUserRecord
     */
    public CUserRecord(UUID id, String username, String email, String password, OffsetDateTime createdAt, OffsetDateTime updatedAt, String userRole) {
        super(CUser.C_USER);

        setId(id);
        setUsername(username);
        setEmail(email);
        setPassword(password);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setUserRole(userRole);
        resetTouchedOnNotNull();
    }
}
