/*
 * This file is generated by jOOQ.
 */
package com.example.cacophony.jooq.tables.records;


import com.example.cacophony.jooq.tables.MessageReact;

import java.time.OffsetDateTime;
import java.util.UUID;

import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MessageReactRecord extends TableRecordImpl<MessageReactRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cacophony.message_react.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>cacophony.message_react.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>cacophony.message_react.message_id</code>.
     */
    public void setMessageId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>cacophony.message_react.message_id</code>.
     */
    public UUID getMessageId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>cacophony.message_react.react_id</code>.
     */
    public void setReactId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>cacophony.message_react.react_id</code>.
     */
    public UUID getReactId() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>cacophony.message_react.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(3, value);
    }

    /**
     * Getter for <code>cacophony.message_react.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>cacophony.message_react.created_at</code>.
     */
    public void setCreatedAt(OffsetDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>cacophony.message_react.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MessageReactRecord
     */
    public MessageReactRecord() {
        super(MessageReact.MESSAGE_REACT);
    }

    /**
     * Create a detached, initialised MessageReactRecord
     */
    public MessageReactRecord(UUID id, UUID messageId, UUID reactId, UUID userId, OffsetDateTime createdAt) {
        super(MessageReact.MESSAGE_REACT);

        setId(id);
        setMessageId(messageId);
        setReactId(reactId);
        setUserId(userId);
        setCreatedAt(createdAt);
        resetTouchedOnNotNull();
    }
}
