/*
 * This file is generated by jOOQ.
 */
package com.example.cacophony.jooq.tables.records;

import com.example.cacophony.jooq.tables.UserConversation;

import java.util.UUID;

import org.jooq.impl.TableRecordImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserConversationRecord extends TableRecordImpl<UserConversationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cacophony.user_conversation.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>cacophony.user_conversation.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>cacophony.user_conversation.channel_id</code>.
     */
    public void setChannelId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>cacophony.user_conversation.channel_id</code>.
     */
    public UUID getChannelId() {
        return (UUID) get(1);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserConversationRecord
     */
    public UserConversationRecord() {
        super(UserConversation.USER_CONVERSATION);
    }

    /**
     * Create a detached, initialised UserConversationRecord
     */
    public UserConversationRecord(UUID userId, UUID channelId) {
        super(UserConversation.USER_CONVERSATION);

        setUserId(userId);
        setChannelId(channelId);
        resetTouchedOnNotNull();
    }
}
