/*
 * This file is generated by jOOQ.
 */
package com.example.cacophony.jooq.tables.records;


import com.example.cacophony.jooq.tables.UserRole;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UserRoleRecord extends UpdatableRecordImpl<UserRoleRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>cacophony.user_role.role</code>.
     */
    public void setRole(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>cacophony.user_role.role</code>.
     */
    public String getRole() {
        return (String) get(0);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRoleRecord
     */
    public UserRoleRecord() {
        super(UserRole.USER_ROLE);
    }

    /**
     * Create a detached, initialised UserRoleRecord
     */
    public UserRoleRecord(String role) {
        super(UserRole.USER_ROLE);

        setRole(role);
        resetTouchedOnNotNull();
    }
}
