/*
 * This file is generated by jOOQ.
 */
package com.example.cacophony.jooq.tables;

import com.example.cacophony.jooq.Cacophony;
import com.example.cacophony.jooq.Keys;
import com.example.cacophony.jooq.tables.Conversation.ConversationPath;
import com.example.cacophony.jooq.tables.records.ChatRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Chat extends TableImpl<ChatRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cacophony.chat</code>
     */
    public static final Chat CHAT = new Chat();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ChatRecord> getRecordType() {
        return ChatRecord.class;
    }

    /**
     * The column <code>cacophony.chat.id</code>.
     */
    public final TableField<ChatRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this,
            "");

    /**
     * The column <code>cacophony.chat.name</code>.
     */
    public final TableField<ChatRecord, String> NAME = createField(DSL.name("name"),
            SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>cacophony.chat.description</code>.
     */
    public final TableField<ChatRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.CLOB,
            this, "");

    /**
     * The column <code>cacophony.chat.created_at</code>.
     */
    public final TableField<ChatRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"),
            SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false)
                    .defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)),
            this, "");

    /**
     * The column <code>cacophony.chat.updated_at</code>.
     */
    public final TableField<ChatRecord, OffsetDateTime> UPDATED_AT = createField(DSL.name("updated_at"),
            SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false)
                    .defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)),
            this, "");

    private Chat(Name alias, Table<ChatRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Chat(Name alias, Table<ChatRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>cacophony.chat</code> table reference
     */
    public Chat(String alias) {
        this(DSL.name(alias), CHAT);
    }

    /**
     * Create an aliased <code>cacophony.chat</code> table reference
     */
    public Chat(Name alias) {
        this(alias, CHAT);
    }

    /**
     * Create a <code>cacophony.chat</code> table reference
     */
    public Chat() {
        this(DSL.name("chat"), null);
    }

    public <O extends Record> Chat(Table<O> path, ForeignKey<O, ChatRecord> childPath,
            InverseForeignKey<O, ChatRecord> parentPath) {
        super(path, childPath, parentPath, CHAT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class ChatPath extends Chat implements Path<ChatRecord> {

        private static final long serialVersionUID = 1L;

        public <O extends Record> ChatPath(Table<O> path, ForeignKey<O, ChatRecord> childPath,
                InverseForeignKey<O, ChatRecord> parentPath) {
            super(path, childPath, parentPath);
        }

        private ChatPath(Name alias, Table<ChatRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public ChatPath as(String alias) {
            return new ChatPath(DSL.name(alias), this);
        }

        @Override
        public ChatPath as(Name alias) {
            return new ChatPath(alias, this);
        }

        @Override
        public ChatPath as(Table<?> alias) {
            return new ChatPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Cacophony.CACOPHONY;
    }

    @Override
    public UniqueKey<ChatRecord> getPrimaryKey() {
        return Keys.CHAT_PKEY;
    }

    @Override
    public List<ForeignKey<ChatRecord, ?>> getReferences() {
        return Arrays.asList(Keys.CHAT__FK_CHAT_CONVERSATION);
    }

    private transient ConversationPath _conversation;

    /**
     * Get the implicit join path to the <code>cacophony.conversation</code> table.
     */
    public ConversationPath conversation() {
        if (_conversation == null)
            _conversation = new ConversationPath(this, Keys.CHAT__FK_CHAT_CONVERSATION, null);

        return _conversation;
    }

    @Override
    public Chat as(String alias) {
        return new Chat(DSL.name(alias), this);
    }

    @Override
    public Chat as(Name alias) {
        return new Chat(alias, this);
    }

    @Override
    public Chat as(Table<?> alias) {
        return new Chat(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Chat rename(String name) {
        return new Chat(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Chat rename(Name name) {
        return new Chat(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Chat rename(Table<?> name) {
        return new Chat(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Chat where(Condition condition) {
        return new Chat(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Chat where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Chat where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Chat where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Chat where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Chat where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Chat where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Chat where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Chat whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Chat whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
