/*
 * This file is generated by jOOQ.
 */
package com.example.cacophony.jooq.tables;

import com.example.cacophony.jooq.Cacophony;
import com.example.cacophony.jooq.Keys;
import com.example.cacophony.jooq.tables.CUser.CUserPath;
import com.example.cacophony.jooq.tables.Message.MessagePath;
import com.example.cacophony.jooq.tables.React.ReactPath;
import com.example.cacophony.jooq.tables.records.MessageReactRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class MessageReact extends TableImpl<MessageReactRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>cacophony.message_react</code>
     */
    public static final MessageReact MESSAGE_REACT = new MessageReact();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<MessageReactRecord> getRecordType() {
        return MessageReactRecord.class;
    }

    /**
     * The column <code>cacophony.message_react.id</code>.
     */
    public final TableField<MessageReactRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>cacophony.message_react.message_id</code>.
     */
    public final TableField<MessageReactRecord, UUID> MESSAGE_ID = createField(DSL.name("message_id"), SQLDataType.UUID,
            this, "");

    /**
     * The column <code>cacophony.message_react.react_id</code>.
     */
    public final TableField<MessageReactRecord, UUID> REACT_ID = createField(DSL.name("react_id"), SQLDataType.UUID,
            this, "");

    /**
     * The column <code>cacophony.message_react.user_id</code>.
     */
    public final TableField<MessageReactRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID, this,
            "");

    /**
     * The column <code>cacophony.message_react.created_at</code>.
     */
    public final TableField<MessageReactRecord, OffsetDateTime> CREATED_AT = createField(DSL.name("created_at"),
            SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(
                    DSL.field(DSL.raw("CURRENT_TIMESTAMP"), SQLDataType.TIMESTAMPWITHTIMEZONE)),
            this, "");

    private MessageReact(Name alias, Table<MessageReactRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private MessageReact(Name alias, Table<MessageReactRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>cacophony.message_react</code> table reference
     */
    public MessageReact(String alias) {
        this(DSL.name(alias), MESSAGE_REACT);
    }

    /**
     * Create an aliased <code>cacophony.message_react</code> table reference
     */
    public MessageReact(Name alias) {
        this(alias, MESSAGE_REACT);
    }

    /**
     * Create a <code>cacophony.message_react</code> table reference
     */
    public MessageReact() {
        this(DSL.name("message_react"), null);
    }

    public <O extends Record> MessageReact(Table<O> path, ForeignKey<O, MessageReactRecord> childPath,
            InverseForeignKey<O, MessageReactRecord> parentPath) {
        super(path, childPath, parentPath, MESSAGE_REACT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class MessageReactPath extends MessageReact implements Path<MessageReactRecord> {

        private static final long serialVersionUID = 1L;

        public <O extends Record> MessageReactPath(Table<O> path, ForeignKey<O, MessageReactRecord> childPath,
                InverseForeignKey<O, MessageReactRecord> parentPath) {
            super(path, childPath, parentPath);
        }

        private MessageReactPath(Name alias, Table<MessageReactRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public MessageReactPath as(String alias) {
            return new MessageReactPath(DSL.name(alias), this);
        }

        @Override
        public MessageReactPath as(Name alias) {
            return new MessageReactPath(alias, this);
        }

        @Override
        public MessageReactPath as(Table<?> alias) {
            return new MessageReactPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Cacophony.CACOPHONY;
    }

    @Override
    public List<ForeignKey<MessageReactRecord, ?>> getReferences() {
        return Arrays.asList(Keys.MESSAGE_REACT__MESSAGE_REACT_MESSAGE_ID_FKEY,
                Keys.MESSAGE_REACT__MESSAGE_REACT_REACT_ID_FKEY, Keys.MESSAGE_REACT__MESSAGE_REACT_USER_ID_FKEY);
    }

    private transient MessagePath _message;

    /**
     * Get the implicit join path to the <code>cacophony.message</code> table.
     */
    public MessagePath message() {
        if (_message == null)
            _message = new MessagePath(this, Keys.MESSAGE_REACT__MESSAGE_REACT_MESSAGE_ID_FKEY, null);

        return _message;
    }

    private transient ReactPath _react;

    /**
     * Get the implicit join path to the <code>cacophony.react</code> table.
     */
    public ReactPath react() {
        if (_react == null)
            _react = new ReactPath(this, Keys.MESSAGE_REACT__MESSAGE_REACT_REACT_ID_FKEY, null);

        return _react;
    }

    private transient CUserPath _cUser;

    /**
     * Get the implicit join path to the <code>cacophony.c_user</code> table.
     */
    public CUserPath cUser() {
        if (_cUser == null)
            _cUser = new CUserPath(this, Keys.MESSAGE_REACT__MESSAGE_REACT_USER_ID_FKEY, null);

        return _cUser;
    }

    @Override
    public MessageReact as(String alias) {
        return new MessageReact(DSL.name(alias), this);
    }

    @Override
    public MessageReact as(Name alias) {
        return new MessageReact(alias, this);
    }

    @Override
    public MessageReact as(Table<?> alias) {
        return new MessageReact(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public MessageReact rename(String name) {
        return new MessageReact(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public MessageReact rename(Name name) {
        return new MessageReact(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public MessageReact rename(Table<?> name) {
        return new MessageReact(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MessageReact where(Condition condition) {
        return new MessageReact(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MessageReact where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MessageReact where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MessageReact where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MessageReact where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MessageReact where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MessageReact where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public MessageReact where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MessageReact whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public MessageReact whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
